name: AntiFarmDrop
version: 1.0
main: com.xuvigan.antifarmdrop.AntiFarmDropPlugin
api-version: 1.21
author: XuViGaN
description: >
  AntiFarmDrop — это продвинутый плагин для защиты от фарма предметов и опыта,
  получаемых от мобов с помощью убийства, ловушек или небоевого урона (огонь, лава и т.д.).
   
  Плагин отслеживает поведение мобов, блокирует дроп в подозрительных ситуациях
  и позволяет другим плагинам взаимодействовать с ним через кастомные события API.
