# 📏 Минимальная высота падения, начиная с которой дроп будет считаться подозрительным.
# Например: если моб упал более чем на 2 блока — он считается упавшим.
min-fall-height: 2.0

# ⏱️ Максимальное время (в миллисекундах), в течение которого отслеживается падение моба.
# После этого информация очищается, чтобы не перегружать память.
max-track-time: 15000 # 15 секунд

# 💥 Причины урона, которые считаются подозрительными (если моб не умирал от игрока).
# Если моб получил урон от одного из этих источников, он может попасть под блокировку дропа.
blocked-damage-causes:
  - FALL         # Урон от падения
  - LAVA         # Лава
  - FIRE         # Обычный огонь
  - FIRE_TICK    # Постоянный урон от огня
  - DROWNING     # Утопление
  - VOID         # Падение в бездну

# 🚫 Список сущностей, которые полностью игнорируются плагином.
# Они не отслеживаются и никогда не блокируются (например, ArmorStand или жители).
excluded-entities:
  - ARMOR_STAND
  - VILLAGER

# 🛑 Включение логирования блокировки дропа в консоль сервера.
# Рекомендуется включать для отладки или на PvE-серверах.
log-blocked-drops: true
